### ISSUE TITLE
Unable to debug 

### ISSUE THREAD

**Issue by dj90sz** [pavel-purma/vscode-mocha-test-runner#11]
There was a vscode update a few weeks ago that seems to break the debug function.

![Error](https://user-images.githubusercontent.com/1513362/30679450-0368f368-9edd-11e7-92a6-2c176a2b552a.png)

Running the test through code lens without debugging still works fine. 
Running the test through code lens with debugging will trigger that error message, however the test will still run.

Any idea how to fix it?

**Comment by cgestes** [comment]
+1

@dj90sz any progress on the subject?

**Comment by CzBuCHi** [comment]
finnaly get some time to owrk on this again ... 
i tweaked how test process is forked and on my machine debug works again (vscode 1.17.0), sadly im not on computer, that can publish new npm package - i should get new version soon(ish) TM ...

**Comment by cgestes** [comment]
I tried and it doesn't work (at least on linux). I can't figure out why.

I did put nodeExec to /usr/bin/node. I run vscode 1.17.

If I run the test It executes TestProcess but all the tests are always marked as fail.

If I click on debug I get:
```
Exception has occurred: Error
Error: channel closed
	at ChildProcess.target.send (internal/child_process.js:562:16)
	at Timeout.setTimeout [as _onTimeout] (/home/cedric/src/vscode-mocha-test-runner/src/TestRunner.ts:133:30)
	at ontimeout (timers.js:386:14)
	at tryOnTimeout (timers.js:250:5)
	at Timer.listOnTimeout (timers.js:214:5)
```

any idea how to investigate?

**Comment by cgestes** [comment]
btw is there a way to debug the TestProcess part of the code?

**Comment by CzBuCHi** [comment]
how did u manage to test it? only way i know of is clone this repo, open in vscode and start debugging it (with open second vscode where u open test project with shows code lens and u can test it)

but in my case i get debugger stop on "use strict" line in "out/src/testProcess.js" ...

"channel closed" error was due my code sending SIGTERM signal to child process when something gets in stderr (i had there if ("data.startsWith('Warning:')) to redirect it to stdout, but rescently there seems to be also "Debugger listening on ..." message with wasnt redirected

**Comment by CzBuCHi** [comment]
just published npm package 0.3.0 ... with works on my 2 machines (both windows 10 soo ... good luck :)

**Comment by dj90sz** [comment]
I haven't had time to look into this, but I did install the latest update (0.3.1) and it stops working altogether on mac :(

**Comment by CzBuCHi** [comment]
@dj90sz sorry about that - i dont have any mac/linux system to test it on so i cannot even start figuring out why it stops working ... can u test it for me or dont have spare time?

**Comment by cgestes** [comment]
@CzBuCHi I test it just like you said. But I cannot break into the test process and still didn't crack how to drive it.

**Comment by CzBuCHi** [comment]
im able to get debugger into test process by starting test in debug mode (2 debugger instances - one for extension and second one started by that extension for test process)

**Comment by cgestes** [comment]
Yeah finally understood that. The debugger doesn't attach when I click on 'debug' on a testcase. But I was able to manually attach.
